#!/bin/bash

pass=0
fail=0

echo "Enter number of students:"
read n

for ((i=1; i<=n; i++)); do
    echo "----------------------"
    echo "Enter Student ID:"
    read sid

    echo "Enter marks of 3 subjects:"
    read m1 m2 m3

    total=$((m1 + m2 + m3))
    percentage=$((total * 100 / 300))

    if [ $percentage -ge 80 ]; then
        grade="A+"
        pass=$((pass + 1))
    elif [ $percentage -ge 70 ]; then
        grade="A"
        pass=$((pass + 1))
    elif [ $percentage -ge 60 ]; then
        grade="B"
        pass=$((pass + 1))
    elif [ $percentage -ge 50 ]; then
        grade="C"
        pass=$((pass + 1))
    else
        grade="F"
        fail=$((fail + 1))
    fi

    echo "Student ID: $sid"
    echo "Total Marks: $total"
    echo "Percentage: $percentage%"
    echo "Grade: $grade"
done

echo "======================="
echo "Final Summary"
echo "Passed Students: $pass"
echo "Failed Students: $fail"
